name: SSH
on:
  workflow_dispatch:
    inputs:
      DeviceTree_Name:
        description: 'start'
        required: true
        default: 'start'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
